apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-store
  namespace: {{.Values.deployParams.AKS_AIRFLOW_NAMESPACE}}
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{.Values.deployParams.KEYVAULT_URL}}
      serviceAccountRef:
        name: {{.Values.deployParams.SERVICE_ACCOUNT_NAME}}