# Nome personalizado para os recursos do Helm
fullnameOverride: "airflow"
nameOverride: "airflow"

env: dev
image:
  repository: airflow
  tag: latest
  pullPolicy: Always



# Definição do Executor (Celery + Kubernetes)
executor: CeleryKubernetesExecutor

# Configuração de nós e tolerâncias
nodeSelector:
    agentpool: devpool

tolerations:
- key: "airflow"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

# Segurança e criptografia
webserverSecretKey: "airflow-secret"
fernetKey: "o-O6e1855-1BMUExNeD7K9ZwOyDsd6akvYtQiaHmyeg="  

# Configuração do Airflow
config:
  core:
    load_examples: 'False'
    load_default_connections: 'False'
    test_connection: 'Enabled'
  webserver:
    rbac: 'True'
    expose_config: 'True'
  logging:
    remote_logging: 'True'
    remote_log_conn_id: "google_cloud_default"
    remote_base_log_folder: "gs://my-application-logs/airflow-logs/dev"
  api:
    auth_backend: "airflow.api.auth.backend.basic_auth"
    enable_experimental_api: 'True'
  celery:
     worker_concurrency: 10
     broker_url: ""
  kubernetes:
    pod_template_file: /opt/airflow/pod_templates/pod_template_file.yaml

# Configuração do GitSync para sincronizar DAGs do repositório
dags:
  gitSync:
    enabled: true
    repo: https://github.com/lucasvittal2/airflow-env/tree/dags
    branch: hml
    rev: HEAD
    subPath: airflow/dags
    depth: 1
    wait: 30

# Configuração do Scheduler
scheduler:
  replicas: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  nodeSelector:
    agentpool: devpool
  tolerations:
    - key: "airflow"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

# Configuração do Webserver
webserver:
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  defaultUser:
    enabled: false
  startupProbe:
    timeoutSeconds: 20
    failureThreshold: 12
    periodSeconds: 15
    scheme: HTTP



# Banco de Dados - Cloud SQL Externo
postgresql:
  enabled: false

data:
  metadataSecretName: airflow-secret

redis:
  enabled: true
  password: "TenSLineArYmErCHarKLERNoiDgere"

# Configuração dos Workers do Celery
workers:
  replicas: 2  # Número de Workers
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
    nodeSelector:
      agentpool: devpool
  tolerations:
    - key: "airflow"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"



# Configuração do Triggerer (para DAGs assíncronas)
triggerer:
  enabled: true

# Configuração do Flower (UI para monitoramento do Celery)
flower:
  enabled: true

# Configuração do Ingress (se necessário)
ingress:
  enabled: false


# Configuração do Job de criação de usuários
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

# Configuração da Migração do Banco de Dados
migrateDatabaseJob:
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync
  useHelmHooks: false
  applyCustomEnv: false
