apiVersion: v2
name: custom-airflow
description: Custom Airflow deployment with external secrets
version: 0.1.0
dependencies:
  - name: airflow
    version: "1.15.0"
    repository: "https://airflow.apache.org"