webserverSecretKey: f1023ed56bd3eb8ee2b069c5eec748b5
deployParams:
  AKS_AIRFLOW_NAMESPACE: airflow
  AZ_TENANT_ID: 7baa26da-48a3-448d-baf2-1ec8a164b2e6
  SERVICE_ACCOUNT_NAME: airflow
  MY_IDENTITY_NAME: airflow-identity-dev
  KEYVAULT_URL: https://airflow-vault-dev-kv.vault.azure.net/
  AKS_AIRFLOW_LOGS_STORAGE_SECRET_NAME: storage-account-credentials
  AKS_AIRFLOW_LOGS_STORAGE_CONTAINER_NAME: airflow-logs
  AKS_AIRFLOW_LOGS_STORAGE_ACCOUNT_NAME : airflowsasadev
  MY_RESOURCE_GROUP_NAME: apache-airflow-dev
  MY_IDENTITY_NAME_CLIENT_ID: 56ba9f36-0feb-47ff-b740-846b0ffd2454
  TENANT_ID: 7baa26da-48a3-448d-baf2-1ec8a164b2e6
  KEYVAULTURL: https://airflow-vault-dev-kv.vault.azure.net/

images:
  airflow:
    repository: airflowregistrydev.azurecr.io/airflow
    tag: 2.9.3
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent
  # To avoid images with user code, you can turn this to 'true' and
  # all the 'run-airflow-migrations' and 'wait-for-airflow-migrations' containers/jobs
  # will use the images from 'defaultAirflowRepository:defaultAirflowTag' values
  # to run and wait for DB migrations .
  useDefaultImageForMigration: false
  # timeout (in seconds) for airflow-migrations to complete
  migrationsWaitTimeout: 60
  pod_template:
    # Note that \`images.pod_template.repository\` and \`images.pod_template.tag\` parameters
    # can be overridden in \`config.kubernetes\` section. So for these parameters to have effect
    # \`config.kubernetes.worker_container_repository\` and \`config.kubernetes.worker_container_tag\`
    # must be not set .
    repository: airflowregistrydev.azurecr.io/airflow
    tag: 2.9.3
    pullPolicy: IfNotPresent
  flower:
    repository: airflowregistrydev.azurecr.io/airflow
    tag: 2.9.3
    pullPolicy: IfNotPresent
  statsd:
    repository: airflowregistrydev.azurecr.io/statsd-exporter
    tag: v0.26.1
    pullPolicy: IfNotPresent
  pgbouncer:
    repository: airflowregistrydev.azurecr.io/airflow
    tag: airflow-pgbouncer-2024.01.19-1.21.0
    pullPolicy: IfNotPresent
  pgbouncerExporter:
    repository: airflowregistrydev.azurecr.io/airflow
    tag: airflow-pgbouncer-exporter-2024.06.18-0.17.0
    pullPolicy: IfNotPresent
  gitSync:
    repository: airflowregistrydev.azurecr.io/git-sync
    tag: v4.1.0
    pullPolicy: IfNotPresent

# Airflow executor
executor: "KubernetesExecutor"

# Environment variables for all airflow containers
env:
  - name: ENVIRONMENT
    value: dev

extraEnv: |
  - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
    value: 'America/New_York'

# Configuration for postgresql subchart
# Not recommended for production! Instead, spin up your own Postgresql server and use the \`data\` attribute in this
# yaml file.
postgresql:
  enabled: true

# Enable pgbouncer. See https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#pgbouncer
pgbouncer:
  enabled: true

dags:
  gitSync:
    enabled: true
    repo: https://github.com/donhighmsft/airflowexamples.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    sshKeySecret: airflow-git-ssh-secret
    knownHosts: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=

logs:
  persistence:
    enabled: true
    existingClaim: pvc-airflow-logs
    storageClassName: azureblob-fuse-premium

# We disable the log groomer sidecar because we use Azure Blob Storage for logs, with lifecyle policy set.
triggerer:
  logGroomerSidecar:
    enabled: false

scheduler:
  logGroomerSidecar:
    enabled: false

workers:
  logGroomerSidecar:
    enabled: false
