apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "6a971a48-80a3-442d-b179-19bfcf5ceb22"
    azure.workload.identity/tenant-id: "7baa26da-48a3-448d-baf2-1ec8a164b2e6"
  name: "airflow"
  namespace: "airflow"