apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-pod-template
  namespace: airflow
data:
  pod_template_file.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: airflow-worker-template
      labels:
        tier: airflow
        component: worker
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      serviceAccountName: airflow-worker
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      containers:
        - name: base
          image: "{{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}"
          imagePullPolicy: "{{ .Values.images.airflow.pullPolicy }}"
          command:
            - "bash"
            - "-c"
            - "exec airflow worker"
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "KubernetesExecutor"
            - name: AIRFLOW__KUBERNETES__NAMESPACE
              value: "{{ .Release.Namespace }}"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"