apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: airflow
  namespace: argocd
spec:
  generators:
    - clusters:
        values:
          stage: homologation
          revision: main
          namespace: airflow
  template:
    metadata:
      name: airflow
      namespace: airflow
      labels:
          appid: airflow
    spec:
      nodePlacement:
        nodeSelector:
          airflow: "true"
        tolerations:
        - key: "airflow"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      project: gitops
      sources:
        - repoURL: 'https://github.com/lucasvittal2/mydevops'
          path: helms/airflow
          targetRevision: main
          helm:
            releaseName: "airflow"
            valueFiles:
              - $values/helm/values.yaml
        - repoURL: 'https://github.com/lucasvittal2/airflow-env'
          targetRevision: dev
          ref: airflow/values
        - repoURL: 'https://github.com/lucasvittal2/airflow-env'
          targetRevision: dev
          path: airflow/homologation
          directory:
            recurse: false
            jsonnet: {}
            exclude: '{homologation.yaml, values.yaml}'
      destination:
        server: '{{server}}'
        namespace: airflow
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: 'true'
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true