
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-secret
  namespace: airflow
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: airflow-secret
  data:
    - secretKey: connection
      remoteRef:
        key: corp-airflow-db-string-connection
    - secretKey: GITSYNC_PASSWORD
      remoteRef:
          key: corp-airflow-gitsync-password
    - secretKey: GITSYNC_USERNAME
      remoteRef:
          key: corp-airflow-gitsync-user
    - secretKey: GIT_SYNC_PASSWORD
      remoteRef:
          key: corp-airflow-gitsync-password
    - secretKey: GIT_SYNC_USERNAME
      remoteRef:
          key: corp-airflow-gitsync-user
    - secretKey: fernet-key
      remoteRef:
          key: corp-airflow-fernet-key
    - secretKey: webserver-key
      remoteRef:
          key: corp-airflow-webserver-key